"""empty message

Revision ID: 2c2d7279e00a
Revises: 3dbac8eeabd8
Create Date: 2026-09-16 10:35:40.675342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2d7279e00a'
down_revision = '3dbac8eeabd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements_total', sa.Integer(), nullable=False,server_default='0'))
        batch_op.add_column(sa.Column('achievements_unlocked', sa.Integer(), nullable=False,server_default='0'))
        batch_op.add_column(sa.Column('achievement_percentage', sa.Float(), nullable=False,server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.drop_column('achievement_percentage')
        batch_op.drop_column('achievements_unlocked')
        batch_op.drop_column('achievements_total')

    op.drop_table('user_achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
