"""empty message

Revision ID: 308a762b10f5
Revises: 0763d677d453
Create Date: 2026-08-26 12:06:38.717422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308a762b10f5'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_friend_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_friend_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('nickname', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('profile_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['steam_id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_url')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('nickname')
        batch_op.drop_column('steam_id')

    op.drop_table('friends')
    # ### end Alembic commands ###
