"""empty message

Revision ID: 37b352bf427a
Revises: 2c2d7279e00a
Create Date: 2026-09-18 09:39:13.836144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b352bf427a'
down_revision = '2c2d7279e00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'appid', name='uq_favorite_user_appid')
    )
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_game', ['user_id', 'game_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_game', type_='unique')

    op.drop_table('favorite')
    # ### end Alembic commands ###
