"""empty message

Revision ID: 808c4c58c684
Revises: 37b352bf427a
Create Date: 2026-09-23 17:46:34.247173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808c4c58c684'
down_revision = '37b352bf427a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('global_percentage')

    # ### end Alembic commands ###
