"""empty message

Revision ID: 9674cd649ae6
Revises: d4cb46a4c001
Create Date: 2026-08-31 09:58:17.774476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9674cd649ae6'
down_revision = 'd4cb46a4c001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('profile_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
