"""empty message

Revision ID: d4cb46a4c001
Revises: e35034f8bd68
Create Date: 2026-08-28 09:36:31.125226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cb46a4c001'
down_revision = 'e35034f8bd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_steam_id_key'), type_='unique')
        batch_op.drop_column('steam_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('user_steam_id_key'), ['steam_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('steam_account')
    # ### end Alembic commands ###
